#!/usr/bin/env python3
"""Bundle one test run into a single markdown file for analysis.

    python .claude/scripts/report.py TEST-115 > run3.md
    python .claude/scripts/report.py TEST-115 --draft draft.txt > run3.md

Collects: the ticket as fetched, every session record with its full extracted
reasoning, the diff stat, the gate prompt in force, and - if you saved it - the
draft the command produced. One file, enough for someone who was not there to
judge the result.

Save the draft by copying it into a text file and passing --draft. The command
prints it to the terminal; nothing captures it automatically.
"""
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
import notes  # noqa: E402

# Redirecting to a file on Windows otherwise writes the console codepage, which
# mangles every em dash the gate produced.
try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

FIELDS = (("decisions", "DECISION"), ("constraints", "CONSTRAINT"),
          ("rejected", "REJECTED"), ("deferred", "DEFERRED"))


def sh(args):
    try:
        p = subprocess.run(args, capture_output=True, text=True, cwd=REPO,
                           timeout=60)
        return (p.stdout or "").strip() or "(no output)"
    except Exception as exc:
        return "(failed: %r)" % exc


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    ticket = args[0] if args else "(no ticket given)"

    draft = None
    if "--draft" in sys.argv:
        i = sys.argv.index("--draft")
        if i + 1 < len(sys.argv):
            try:
                draft = open(sys.argv[i + 1], encoding="utf-8").read()
            except Exception as exc:
                draft = "(could not read draft file: %r)" % exc

    out = []
    w = out.append

    w("# Capture test run -- %s" % ticket)
    w("")
    w("Generated by `report.py`. Everything below is what the run actually")
    w("produced; no commentary added.")
    w("")

    w("## The ticket, as the tool read it")
    w("")
    w("```")
    w(sh(["python", os.path.join(HERE, "ticket_context.py"), ticket]))
    w("```")
    w("")

    records = notes.load_records()
    w("## Session records (%d)" % len(records))
    w("")
    if not records:
        w("_No records captured._")
    for i, r in enumerate(records, 1):
        state = "POSTED to %s" % r.get("posted_to", "?") if r.get("posted") \
            else "unposted"
        w("### [%d] %s -- %s" % (i, (r.get("session_id") or "?")[:8], state))
        w("")
        w("- ended: `%s`  turns: `%s`  gate: `%s`"
          % (r.get("ended"), r.get("turns"), r.get("gate")))
        if r.get("skip_reason"):
            w("- skip_reason: `%s`" % r["skip_reason"])
        if r.get("ticket_hint"):
            w("- ticket named in session: `%s`" % r["ticket_hint"])
        if r.get("files"):
            w("- files touched: %s" % ", ".join("`%s`" % f for f in r["files"]))
        if r.get("error"):
            w("- error: `%s`" % r["error"])
        w("")
        if r.get("summary"):
            w("**%s**" % r["summary"])
            w("")
        any_items = False
        for key, label in FIELDS:
            for item in r.get(key) or []:
                w("- **%s** -- %s" % (label, item))
                any_items = True
        if not any_items:
            w("_No items extracted._")
        w("")
        if r.get("transcript_path"):
            w("<sub>transcript: `%s`</sub>" % r["transcript_path"])
            w("")

    w("## Working copy at draft time")
    w("")
    w("```")
    w(sh(["git", "status", "--short"]))
    w("```")
    w("")
    w("```")
    w(sh(["git", "diff", "HEAD", "--stat"]))
    w("```")
    w("")

    if draft is not None:
        w("## The draft it produced")
        w("")
        w("```")
        w(draft.strip())
        w("```")
        w("")

    w("## Gate prompt in force for this run")
    w("")
    w("```")
    try:
        w(open(os.path.join(HERE, "worker_prompt.txt"), encoding="utf-8")
          .read().strip())
    except Exception as exc:
        w("(could not read: %r)" % exc)
    w("```")
    w("")

    w("## Tooling version")
    w("")
    w("```")
    w(sh(["git", "log", "--oneline", "-5"]))
    w("```")
    w("")

    w("## Questions for whoever analyses this")
    w("")
    w("1. Is anything **missing** from the records -- a decision made in a")
    w("   session that no record contains? This is the failure that matters,")
    w("   because it cannot be recovered once the session is over.")
    w("2. Is anything **junk** -- meta-observations, or restatements of what the")
    w("   code already shows?")
    w("3. Was **attribution** right, and were its exclusions explained well")
    w("   enough to catch a wrong call?")
    w("4. Could the `Why` have been written from the diff alone? If yes, the")
    w("   capture is not earning its keep.")
    w("5. Where the record was incomplete, did the draft **say so**?")

    print("\n".join(out))


if __name__ == "__main__":
    main()
